Literature_paper_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Paper_Chat.urls')),
    path('Paper_Finder/', include('Paper_Finder.urls')),
    path('Paper_Extractor/', include('Paper_Extractor.urls', namespace='Paper_Extractor')),
    path('Paper_Search/', include('Paper_Search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paper_Chat/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.homepage, name='homepage'),  # New centralized homepage
    path('pdf_chat/', views.index, name='index'),  # Previous main page of pdf_chat
    path('upload_pdf/', views.upload_pdf, name='upload_pdf'),
    path('process_text/', views.process_text, name='process_text'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paper_Extractor/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView
from .views import download_excel


app_name = 'Paper_Extractor'

urlpatterns = [
    path('', RedirectView.as_view(url='extract/'), name='root_redirect'),
    path('extract/', views.display_upload_page, name='display_upload'),
    path('start_extraction/', views.process_and_display_results, name='extract_dois'),
    path('upload/', views.upload_pdf_view, name='upload_pdf'),
    path('delete/<int:pdf_id>/', views.delete_pdf_view, name='delete_pdf'),
    path('download_excel/', download_excel, name='download_excel'),

]

pdf_processor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('text_processor.urls')),
    path('literature_finder/', include('literature_finder.urls')),
    path('paper_extract/', include('paper_extract.urls', namespace='paper_extract')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Paper_Extractor/models.py
from django.db import models
import os

class UploadedPDF(models.Model):
    pdf_file = models.FileField(upload_to='uploaded_pdfs/')
    upload_time = models.DateTimeField(auto_now_add=True)
    @property
    def file_name(self):
        return os.path.basename(self.pdf_file.name)

Paper_Extractor/forms.py
from django import forms
from .models import UploadedPDF

class PDFUploadForm(forms.ModelForm):
    pdf_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), label="Upload PDFs")

    class Meta:
        model = UploadedPDF
        fields = ['pdf_file']

Paper_Extractor/views.py
from django.shortcuts import render, redirect
from .forms import PDFUploadForm
from .models import UploadedPDF
from .Hybrid_method import extract_doi_from_pdf_using_ocr, get_paper_info, extract_doi_from_pdf_text
from django.urls import reverse
import os
from django.conf import settings
import pandas as pd
from django.http import HttpResponse
import io

def upload_pdf_view(request):
    all_pdfs = UploadedPDF.objects.all()  
    if request.method == 'POST':
        form = PDFUploadForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('pdf_file')
            for file in files:
                instance = UploadedPDF(pdf_file=file)
                instance.save()
            return redirect('Paper_Extractor:upload_pdf')
    else:
        form = PDFUploadForm()
    return render(request, 'Paper_Extractor/upload.html', {'form': form, 'all_pdfs': all_pdfs})

def delete_pdf_view(request, pdf_id):
    pdf_to_delete = UploadedPDF.objects.get(id=pdf_id)
    file_path = os.path.join(settings.MEDIA_ROOT, pdf_to_delete.pdf_file.name)
    if os.path.exists(file_path):
        os.remove(file_path)
    pdf_to_delete.delete()
    return redirect(reverse('Paper_Extractor:upload_pdf'))

def display_upload_page(request):
    all_pdfs = UploadedPDF.objects.all()
    return render(request, 'Paper_Extractor/upload.html', {'all_pdfs': all_pdfs})

def process_and_display_results(request):
    all_doi_results = []
    all_paper_info = []
    all_pdfs = UploadedPDF.objects.all()
    for pdf in all_pdfs:
        if not os.path.exists(pdf.pdf_file.path):
            continue
        primary_doi = extract_doi_from_pdf_text(pdf.pdf_file.path)
        if primary_doi:
            paper_details = get_paper_info(primary_doi)
            valid_data = paper_details[0] != "N/A"
        else:
            valid_data = False
        if not valid_data:
            extracted_dois = extract_doi_from_pdf_using_ocr(pdf.pdf_file.path)
            primary_doi = extracted_dois[0] if extracted_dois else None
            if primary_doi:
                paper_details = get_paper_info(primary_doi)
        if primary_doi:
            all_doi_results.append(primary_doi)
            all_paper_info.append({
                'doi': primary_doi,
                'title': paper_details[2],
                'authors': paper_details[0],
                'abstract': paper_details[4],
                'publication_date': paper_details[1],
                'concepts': paper_details[3],
                'referenced_works': paper_details[5],
                'related_works': paper_details[6]
            })
    return render(request, 'Paper_Extractor/upload.html', {'dois': all_doi_results, 'papers': all_paper_info, 'all_pdfs': all_pdfs})

def download_excel(request):
    all_paper_info = []
    all_pdfs = UploadedPDF.objects.all()
    for pdf in all_pdfs:
        if not os.path.exists(pdf.pdf_file.path):
            continue
        primary_doi = extract_doi_from_pdf_text(pdf.pdf_file.path)
        if primary_doi:
            paper_details = get_paper_info(primary_doi)
            valid_data = paper_details[0] != "N/A"
        else:
            valid_data = False
        if not valid_data:
            extracted_dois = extract_doi_from_pdf_using_ocr(pdf.pdf_file.path)
            primary_doi = extracted_dois[0] if extracted_dois else None
            if primary_doi:
                paper_details = get_paper_info(primary_doi)
        if primary_doi:
            all_paper_info.append({
                'doi': primary_doi,
                'title': paper_details[2],
                'authors': paper_details[0],
                'abstract': paper_details[4],
                'publication_date': paper_details[1],
                'concepts': paper_details[3],
                'referenced_works': paper_details[5],
                'related_works': paper_details[6]
            })
    df = pd.DataFrame(all_paper_info)
    output = io.BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    df.to_excel(writer, sheet_name='Sheet1', index=False)
    writer.save()
    output.seek(0)
    response = HttpResponse(output.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="extracted_papers.xlsx"'
    return response

Paper_Extractor/templates/Paper_Extractor/upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Automated Paper Data Extractor</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f4f4f4;
        }

        .title-bar {
            background-color: #333;
            color: white;
            padding: 10px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 1.3em;
        }

        .title-bar h1 {
            font-weight: 700;
            flex-grow: 1;
            text-align: center;
            font-size: 1.3em;
        }

        .home-link {
            color: white;
            text-decoration: none;
            font-size: 1em;
            margin-right: auto;
            padding-right: 20px;
            border-right: 1px solid white;
        }

        .upload-section {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            background-color: white;
            border-bottom: 2px solid #ddd;
        }

        .info-button {
            background-color: #3498db;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
            font-size: 1em;
            font-weight: 600;
        }

        .info-button:hover {
            background-color: #2980b9;
        }

        .pdf-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: white;
            border-radius: 5px;
        }

        .pdf-table th, .pdf-table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
        }

        .pdf-table th {
            background-color: #f2f2f2;
        }

        .pdf-table tr:hover {
            background-color: #f5f5f5;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: white;
            border-radius: 5px;
        }

        th, td {
            padding: 12px 15px;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tbody tr:hover {
            background-color: #f5f5f5;
        }

        .download-button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0px 30px 20px;
            background-color: #3498db;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
            font-size: 1em;
            font-weight: 600;
        }

        .download-button:hover {
            background-color: #2980b9;
        }

    </style>
</head>

<body>
    <div class="title-bar">
        <a href="/" class="home-link">Homepage</a>
        <h1>Automated Paper Data Extractor</h1>
    </div>
    <div class="upload-section">
        <form action="{% url 'Paper_Extractor:upload_pdf' %}" method="post" enctype="multipart/form-data" style="display: flex; align-items: center; gap: 20px;">
            {% csrf_token %}
            <input type="file" name="pdf_file">
            <input type="submit" value="Upload">
        </form>
        <button class="info-button" onclick="location.href='{% url 'Paper_Extractor:extract_dois' %}'">Get Literature Paper Informations</button>
    </div>

    <h2 style="padding: 20px;">Uploaded PDFs</h2>
    <table class="pdf-table">
        <thead>
            <tr>
                <th>PDF Name</th>
                <th>Upload Time</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for pdf in all_pdfs %}
            <tr>
                <td>{{ pdf.file_name }}</td>
                <td>{{ pdf.upload_time|date:"F j, Y, P" }}</td>
                <td><a href="{% url 'Paper_Extractor:delete_pdf' pdf.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if papers %}
    <h2 style="padding: 20px;">Extracted Paper Details:</h2>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>DOI</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for paper in papers %}
            <!-- Main row displaying essential info -->
            <tr>
                <td>{{ paper.title }}</td>
                <td><a href="https://doi.org/{{ paper.doi }}" target="_blank">{{ paper.doi }}</a></td>
                <td><button onclick="toggleDetails('details-{{ forloop.counter }}')">More Details</button></td>
            </tr>
            <!-- Hidden row for details -->
            <tr id="details-{{ forloop.counter }}" style="display: none;">
                <td colspan="3">
                    <strong>Authors:</strong> {{ paper.authors }}<br>
                    <strong>Abstract:</strong> {{ paper.abstract }}<br>
                    <strong>Publication Date:</strong> {{ paper.publication_date }}<br>
                    <strong>Concepts:</strong> {{ paper.concepts }}<br>
                    <!-- <strong>Referenced Works:</strong> {{ paper.referenced_works }}<br> -->
                    <!-- <strong>Related Works:</strong> {{ paper.related_works }}<br> -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'Paper_Extractor:download_excel' %}" class="download-button">Download Extracted Papers (Excel)</a>
    {% endif %}

    <script>
        function toggleDetails(id) {
            var detailsRow = document.getElementById(id);
            if (detailsRow.style.display === "none") {
                detailsRow.style.display = "";
            } else {
                detailsRow.style.display = "none";
            }
        }
    </script>